### ISSUE TITLE
Interface trouble, eth1 doesn't exist

### ISSUE THREAD

**Issue by MarwaChami** [fnss/fnss#23]
Hello,
I'm totally new to mininet, and I have some problems while testing some tutorials.
The first issue is that I get only one interface although I have followed all the instructions in the tutorials. 
How can I solve this problem?

Thanks in advance.
Regards,
Marwa

**Comment by lorenzosaino** [comment]
Hi Marwa,

You didn't give me enough information to help you out with your problem. Please send me a detailed description of the problem with everything I need to reproduce the issue and I will happily help you out.

Best regards,
Lorenzo
