### ISSUE TITLE
generate management protocols traffic

### ISSUE THREAD

**Issue by EngKhaled91** [fnss/fnss#25]
Hello everybody
I want to evaluate snmp and netconf protocols using network simulator 3 (NS3) as simulator 
but is there any way to generate the previous protocols traffic using fnss and include this in ns3
thanks for responding 
Khaled

**Comment by lorenzosaino** [comment]
Hi Khaled,

Unfortunately it is not possible to generate SNMP or NETCONF traffic in ns-3 using FNSS. FNSS only allows you to create a topology and a schedule of events to use with ns-3. You could still create a network topology with FNSS and then write code to generate SNMP and NETCONFIG traffic.

Please bear in mind that the ns-3 adapter has not been tested with recent versions of ns-3, so you might potentially find some issues.

Hope this helps!
Lorenzo

**Comment by EngKhaled91** [comment]
I'm using NS3.29 (latest version) and follow steps to include fnss-ns3 as tutorial in your website and done successfully.
thanks for responding

**Comment by lorenzosaino** [comment]
Great to know, thanks for the information! Feel free to reach out if you have further questions. 👋
