### ISSUE TITLE
Fnss finding issue finding the updated data center topology

### ISSUE THREAD

**Issue by hktakhar** [fnss/fnss#30]
Hi,

I modified the datacenter.py file under the "local\vne-sim\external-libs\fnss\fnss\topologies" folder and when I compile the changes fnss is not recognizing the newly added topology. The default version of python in my OS is 2.7.17 and it isn't recognizing the new topology. However, when I run python3 it is able to read the newly added topology. I am not able to figure out why python3 is able to recognize the latest updates. I had manually installed fnss using the following commands:

python setup.py install
sudo make install

Please help. Thanks!
<img width="656" alt="fnss" src="https://user-images.githubusercontent.com/37053122/112936742-3d8fbd80-90db-11eb-8cc3-4d74e25df87c.PNG">

**Comment by lorenzosaino** [comment]
Hello,

Without sharing the specific change that you made, I cannot tell what the reason might be. I can only speculate that you may have forgotten to add the new function to the `__all__` list: https://github.com/fnss/fnss/blob/master/fnss/topologies/datacenter.py#L9-L15.

In any case, Python 2.7 reached end of life at the end of 2019. While FNSS still formally support Python 2.7, it will drop support soon, so you might want to consider using Python 3.

I am closing this issue for now, feel free to reopen if you have any further issues

**Comment by hktakhar** [comment]
Hi Lorenzo,

I did add the new function (DCell topology) in _all_ and I have updated all the necessary files such as "datacenter.py", "fnss-handler.h", "experiment-parameters.h", "experiment-parameters.cc". I am not sure how can I currently install fnss for python2.7 as I am using a tool VNE-Sim: http://www.sfu.ca/~ljilja/cnl/projects/VNE-Sim/vne-sim-web/index.html#download for my project. Please suggest how can I install fnss in a way that python 2.7 recognizes the new changes as well.

**Comment by lorenzosaino** [comment]
I am happy to help you but if you don't share with me the code of the change that you made, I have no material to help you. I cannot imagine what's wrong with your code without seeing it. Also, "fnss-handler.h", "experiment-parameters.h", "experiment-parameters.cc" are not files that are part of FNSS: presumably, that's code that's part of VNE-Sim, in which case, you should probably contact VNE-Sim maintainer.
